name: ESRGAN_x2_f64b16_UCML_test
model_type: ESRGANModel
scale: 2
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

datasets:
  test_1:  # the 1st test dataset
    name: UCMerced_LandUse
    type: PairedImageDataset
    dataroot_gt: Data/UCMerced_LandUse/testresampling_05_crop
    dataroot_lq: Data/UCMerced_LandUse/testresampling_05_downx2
    io_backend:
      type: disk


# network structures
network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  num_grow_ch: 32

# path
path:
  pretrain_network_g: ~
  strict_load_g: true

# validation settings
val:
  save_img: true
  suffix: ~  # add suffix to saved images, if None, use exp name

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false